"""Repository contracts and SQLite implementations."""

from repositories.holding_rebuild_uow import SQLiteHoldingRebuildUnitOfWork
from repositories.interfaces import (
    DividendEventRepository,
    DividendRepository,
    FxRateRepository,
    HoldingRebuildRepository,
    HoldingRebuildUnitOfWork,
    HoldingRepository,
    LiabilityRepository,
    MarketDataUnitOfWork,
    PositionSnapshotRepository,
    PriceQuoteRepository,
    ReportDeliveryRepository,
    SnapshotRepository,
    TransactionLedgerRepository,
    TransactionRepository,
    WatchlistRepository,
)
from repositories.market_data_uow import SQLiteMarketDataUnitOfWork
from repositories.postgresql import (
    PostgreSQLDividendEventRepository,
    PostgreSQLDividendRepository,
    PostgreSQLFxRateRepository,
    PostgreSQLHoldingRepository,
    PostgreSQLLiabilityRepository,
    PostgreSQLPositionSnapshotRepository,
    PostgreSQLPriceQuoteRepository,
    PostgreSQLReportDeliveryRepository,
    PostgreSQLSnapshotRepository,
    PostgreSQLTransactionRepository,
    PostgreSQLWatchlistRepository,
)
from repositories.postgresql_uow import (
    PostgreSQLHoldingRebuildUnitOfWork,
    PostgreSQLMarketDataUnitOfWork,
)
from repositories.sqlite import (
    SQLiteDividendEventRepository,
    SQLiteDividendRepository,
    SQLiteFxRateRepository,
    SQLiteHoldingRepository,
    SQLiteLiabilityRepository,
    SQLitePositionSnapshotRepository,
    SQLitePriceQuoteRepository,
    SQLiteReportDeliveryRepository,
    SQLiteSnapshotRepository,
    SQLiteTransactionRepository,
    SQLiteWatchlistRepository,
)

__all__ = [
    "DividendRepository",
    "DividendEventRepository",
    "FxRateRepository",
    "HoldingRepository",
    "HoldingRebuildRepository",
    "HoldingRebuildUnitOfWork",
    "LiabilityRepository",
    "MarketDataUnitOfWork",
    "PositionSnapshotRepository",
    "PostgreSQLDividendRepository",
    "PostgreSQLDividendEventRepository",
    "PostgreSQLFxRateRepository",
    "PostgreSQLHoldingRepository",
    "PostgreSQLHoldingRebuildUnitOfWork",
    "PostgreSQLLiabilityRepository",
    "PostgreSQLMarketDataUnitOfWork",
    "PostgreSQLPositionSnapshotRepository",
    "PostgreSQLPriceQuoteRepository",
    "PostgreSQLReportDeliveryRepository",
    "PostgreSQLSnapshotRepository",
    "PostgreSQLTransactionRepository",
    "PostgreSQLWatchlistRepository",
    "PriceQuoteRepository",
    "ReportDeliveryRepository",
    "SQLiteDividendRepository",
    "SQLiteDividendEventRepository",
    "SQLiteFxRateRepository",
    "SQLiteHoldingRepository",
    "SQLiteHoldingRebuildUnitOfWork",
    "SQLiteLiabilityRepository",
    "SQLiteMarketDataUnitOfWork",
    "SQLitePositionSnapshotRepository",
    "SQLitePriceQuoteRepository",
    "SQLiteReportDeliveryRepository",
    "SQLiteSnapshotRepository",
    "SQLiteTransactionRepository",
    "SQLiteWatchlistRepository",
    "SnapshotRepository",
    "TransactionRepository",
    "TransactionLedgerRepository",
    "WatchlistRepository",
]
