"""Domain-specific repository contracts."""

from contextlib import AbstractContextManager
from datetime import date
from typing import Protocol

from domain import (
    DailySnapshot,
    Dividend,
    Holding,
    Liability,
    PositionSnapshot,
    PriceQuote,
    Transaction,
)


class HoldingRepository(Protocol):
    """Persistence operations required for holdings."""

    def list_all(self) -> list[Holding]: ...
    def get_by_id(self, holding_id: str) -> Holding | None: ...
    def upsert(self, holding: Holding) -> None: ...
    def delete(self, holding_id: str) -> None: ...


class TransactionRepository(Protocol):
    """Persistence operations required for transactions."""

    def list_all(self) -> list[Transaction]: ...
    def get_by_id(self, transaction_id: str) -> Transaction | None: ...
    def list_by_symbol(self, symbol: str) -> list[Transaction]: ...
    def exists(self, transaction_id: str) -> bool: ...
    def list_filtered(
        self,
        *,
        symbol: str | None = None,
        start_date: date | None = None,
        end_date: date | None = None,
    ) -> list[Transaction]: ...
    def add(self, transaction: Transaction) -> None: ...
    def upsert(self, transaction: Transaction) -> None: ...
    def delete(self, transaction_id: str) -> None: ...


class DividendRepository(Protocol):
    """Persistence operations required for dividends."""

    def list_all(self) -> list[Dividend]: ...
    def get_by_id(self, dividend_id: str) -> Dividend | None: ...
    def list_by_symbol(self, symbol: str) -> list[Dividend]: ...
    def upsert(self, dividend: Dividend) -> None: ...
    def delete(self, dividend_id: str) -> None: ...


class LiabilityRepository(Protocol):
    """Persistence operations required for liabilities."""

    def list_all(self) -> list[Liability]: ...
    def get_by_id(self, liability_id: str) -> Liability | None: ...
    def upsert(self, liability: Liability) -> None: ...
    def delete(self, liability_id: str) -> None: ...


class SnapshotRepository(Protocol):
    """Persistence operations required for daily snapshots."""

    def get_by_date(self, snapshot_date: date) -> DailySnapshot | None: ...
    def get_latest(self) -> DailySnapshot | None: ...
    def get_highest(self) -> DailySnapshot | None: ...
    def list_between_dates(self, start: date, end: date) -> list[DailySnapshot]: ...
    def add(self, snapshot: DailySnapshot) -> None: ...


class PriceQuoteRepository(Protocol):
    """Persistence operations required for normalized market prices."""

    def upsert_many(self, quotes: list[PriceQuote]) -> None: ...
    def list_by_date(self, trade_date: date) -> list[PriceQuote]: ...
    def get_latest(self, symbol: str, market: str) -> PriceQuote | None: ...


class PositionSnapshotRepository(Protocol):
    """Persistence operations for holding-level snapshot rows."""

    def add_many(self, snapshots: list[PositionSnapshot]) -> None: ...
    def list_by_date(self, snapshot_date: date) -> list[PositionSnapshot]: ...


class HoldingRebuildRepository(Protocol):
    """Only holding operations permitted during a rebuild."""

    def list_all(self) -> list[Holding]: ...
    def upsert(self, holding: Holding) -> None: ...


class TransactionLedgerRepository(Protocol):
    """Read-only transaction access permitted during a rebuild."""

    def list_all(self) -> list[Transaction]: ...


class HoldingRebuildUnitOfWork(Protocol):
    """Atomic repository boundary for applying a holding rebuild."""

    holdings: HoldingRebuildRepository
    transactions: TransactionLedgerRepository

    def transaction(self) -> AbstractContextManager[None]: ...
