"""Domain-specific repository contracts."""

from datetime import date
from typing import Protocol

from domain import DailySnapshot, Dividend, Holding, Liability, Transaction


class HoldingRepository(Protocol):
    """Persistence operations required for holdings."""

    def list_all(self) -> list[Holding]: ...
    def get_by_id(self, holding_id: str) -> Holding | None: ...
    def upsert(self, holding: Holding) -> None: ...
    def delete(self, holding_id: str) -> None: ...


class TransactionRepository(Protocol):
    """Persistence operations required for transactions."""

    def list_all(self) -> list[Transaction]: ...
    def get_by_id(self, transaction_id: str) -> Transaction | None: ...
    def list_by_symbol(self, symbol: str) -> list[Transaction]: ...
    def upsert(self, transaction: Transaction) -> None: ...
    def delete(self, transaction_id: str) -> None: ...


class DividendRepository(Protocol):
    """Persistence operations required for dividends."""

    def list_all(self) -> list[Dividend]: ...
    def get_by_id(self, dividend_id: str) -> Dividend | None: ...
    def list_by_symbol(self, symbol: str) -> list[Dividend]: ...
    def upsert(self, dividend: Dividend) -> None: ...
    def delete(self, dividend_id: str) -> None: ...


class LiabilityRepository(Protocol):
    """Persistence operations required for liabilities."""

    def list_all(self) -> list[Liability]: ...
    def get_by_id(self, liability_id: str) -> Liability | None: ...
    def upsert(self, liability: Liability) -> None: ...
    def delete(self, liability_id: str) -> None: ...


class SnapshotRepository(Protocol):
    """Persistence operations required for daily snapshots."""

    def get_by_date(self, snapshot_date: date) -> DailySnapshot | None: ...
    def get_latest(self) -> DailySnapshot | None: ...
    def get_highest(self) -> DailySnapshot | None: ...
    def list_between_dates(self, start: date, end: date) -> list[DailySnapshot]: ...
    def add(self, snapshot: DailySnapshot) -> None: ...
